# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0004_auto_20170222_1126'),
        ('course', '0002_auto_20170217_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('class_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginandreg.User')),
            ],
        ),
    ]
