# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0004_auto_20170222_1126'),
        ('course', '0003_usersclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersclass',
            name='class_user',
        ),
        migrations.AddField(
            model_name='class',
            name='users',
            field=models.ManyToManyField(related_name='courses', to='loginandreg.User'),
        ),
        migrations.DeleteModel(
            name='UsersClass',
        ),
    ]
