# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0004_auto_20170222_1126'),
        ('course', '0004_auto_20170222_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_class', to='course.Class')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_users', to='loginandreg.User')),
            ],
        ),
    ]
