# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginandreg', '0002_auto_20170220_2153'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=140),
        ),
    ]
